### ISSUE TITLE
Roadmap :rocket: 

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3108]
Hi,

Here is a list of tasks in priority order :

+ [ ] Disable logging feature => #3052 
+ [ ] Use a ☁️ provider
+ [ ] Create a GraphQL API
+ [ ] Create a custom UI
+ [ ] Add multiple platforms support #1570

Regards,

-------
(Open to discussion)

Regards,

**Comment by septatrix** [comment]
I would also suggest pypy for Python

**Comment by waghanza** [comment]
Thanks for your suggestion. As a global reflexion, I'm not sure it is very useful to check those results for all VMs since it increase a lot the complexity (maintenance) for this project.

For example, we have 28 frameworks in `python`, and checking for :
+ `python`
+ `ironpython`
+ `pypi`
+ `graalpython`

would add 28*3 (+ in case of multiple engines [hypercorn, uvicorn, gunicorn ...])

I think for our sake that we need to stick on a restricted list (what is mainly used)

wdyt @ahopkins @the-benchmarker/web-frameworks ?

**Comment by ahopkins** [comment]
I would say test against the latest version of python that all frameworks support. The bigger question is not _how_ fast a framework _can_ perform. Benchmarks for those numbers are highly suspect and cannot really tell you that since there are too many factors. What benchmarks can give you are an idea of relative performance. For that, we need one baseline version, which should (IMO) be the latest version which all tested frameworks support.

**Comment by waghanza** [comment]
With your comment @ahopkins, and as long as I work on https://github.com/the-benchmarker/web-frameworks/pull/3958, I think that using `variants` is over-engineering.

I mean, in my mind `variants` could be :
- an engine, for example `puma`
- a vm, for example `truffleruby`
- a dialect, for example `jruby`

We have better to introduce only `engines` (the more relevant example is `node` in `javascript`), and introduce vm later

**Comment by SuspiciousLookingOwl** [comment]
> Having a clean UI to expose results (/cc @doanguyen I'll ask for you help when the time will come)

Sorry if this sounds like a self promotion, but I made a web app (using React) to show the data in Chart (filterable by frameworks) and Table (filterable by language and sortable).

![Chart](https://i.ibb.co/QPzzH3L/image.png)
![Table](https://i.ibb.co/4fdhDmW/image.png)

Demo: https://web-frameworks-benchmark.netlify.app/
Repo: https://github.com/SuspiciousLookingOwl/web-frameworks-benchmark

**Comment by waghanza** [comment]
should be promoted in the `README` @SuspiciousLookingOwl 

what do you think @the-benchmarker/web-frameworks ?

**Comment by dalisoft** [comment]
@waghanza I sure it should be in README, looks nice and works good

**Comment by waghanza** [comment]
@SuspiciousLookingOwl your idea seems awesome. I see however that you are parsing `README.md` file directly from github. The `README` was not made for that, then I can break your parsing.

If you prefer, I can export raw data as `json`, and push them (on next result update)

**Comment by SuspiciousLookingOwl** [comment]
I agree that parsing the md file isn't an ideal solution. My target was having the web app to always shows the latest data from this repo without too much hassle on my end.

> If you prefer, I can export raw data as json, and push them (on next result update)

That sounds awesome! It will be great if you can do that 😁

**Comment by waghanza** [comment]
I've created a discussion @SuspiciousLookingOwl
 https://github.com/the-benchmarker/web-frameworks/discussions/4165

**Comment by SuspiciousLookingOwl** [comment]
IMO https://github.com/the-benchmarker/web-frameworks/issues/3803 should also be in the roadmap.

**Comment by waghanza** [comment]
Agree @SuspiciousLookingOwl, I've updated the roadmap

+ I change flavors to engines. Initially I wanted to run all frameworks on various things (like `jruby`, `deno`, `rhino`) but seems too complicated.

**Comment by bung87** [comment]
hey, I have some thoughts after adding my project to this project and https://github.com/TechEmpower/FrameworkBenchmarks  

1. Compare to `TechEmpower/FrameworkBenchmarks` this project does not constrain the http headers.   
2. Newer added framework may take high priority and within its language and platform etc.
3. Compiled language and non-compiled language may results in different categories , generally compiled language will be n `x` faster than non-compiled language

**Comment by waghanza** [comment]
> hey, I have some thoughts after adding my project to this project and https://github.com/TechEmpower/FrameworkBenchmarks

thank you for that ❤️ 

> 1. Compare to `TechEmpower/FrameworkBenchmarks` this project does not constrain the http headers.

not yet, it is planned, but some work have to be done before

> 2. Newer added framework may take high priority and within its language and platform etc.

could you specify you though ? I don't get you here

> 3. Compiled language and non-compiled language may results in different categories , generally compiled language will be n `x` faster than non-compiled language

the idea is **NOT** to show only performances, but all valuable insights (resources consumptions, performances, latencies ...) about frameworks

**Comment by bung87** [comment]
about 2. eg. my project `scorper` just added may run it first then run other frameworks written in `Nim` then run rest frameworks. if any error occurs the author does not need wait for long.

**Comment by cyrusmsk** [comment]
Any news on the Roadmap?

**Comment by waghanza** [comment]
I plan to rewrite readme and to integrate it in a more clear way in `README.md`

**Comment by cyrusmsk** [comment]
> I plan to rewrite readme and to integrate it in a more clear way in `README.md`

Maybe create a task with sub-tasks and somebody also will make a PR for tests improvements?

**Comment by nigrosimone** [comment]
> Having a clean UI to expose results

see https://github.com/the-benchmarker/website/pull/84
